// app/layout.tsx
import type { Metadata } from "next";
import "./styleSheets/layout.css";
import "./styleSheets/antdOverride.css";
import "./styleSheets/commonClasses.css";
import AntdConfigLayout from "./layouts/antdConfigLayout";
import 'antd/dist/reset.css'; 
import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <AntdConfigLayout>
          {children}
        </AntdConfigLayout>
      </body>
    </html>
  );
}