// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import "./layout.css";
import "./antdOverride.css";
import "./commonClasses.css";
import AntdConfigLayout from "./layouts/antdConfigLayout";
import 'antd/dist/reset.css'; 
import ReduxProvider from "./providers/reduxProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link
  href="https://cdn.jsdelivr.net/npm/remixicon@4.9.0/fonts/remixicon.css"
  rel="stylesheet"
/>
      </head>

      <body >
        <ReduxProvider>
          <AntdConfigLayout>
          {children}
        </AntdConfigLayout>
        </ReduxProvider>
        
      </body>
    </html>
  );
}