import type { Metadata } from "next";
import "./globals.css";
import { ConfigProvider } from "antd";
import AntdConfigLayout from "./layouts/antdConfigLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <AntdConfigLayout>{children}</AntdConfigLayout>
    
  );
}
